### ISSUE TITLE
Support for syncing status of built-in extensions

### ISSUE THREAD

**Issue by Cottser** [zokugun/vscode-sync-settings#13]
Thanks for this great extension!

Recently I noticed that the sync doesn't seem to pick up the status (disabled/enabled) of built-in extensions. To use [vscode-intelephense](https://github.com/bmewburn/vscode-intelephense#quick-start) it's recommended to disable one of the built-in vscode extensions.

Steps to reproduce:

1. Go to Extensions (open sidebar panel).
1. Search for `@builtin php`
1. Disable `PHP Language Features`.
1. Sync Settings: Upload (there will be no changes reflected in the repo assuming you're up to date)
1. Sync Settings: Download

Expected result: `PHP Language Features` extension disabled status will either be captured in the settings repo, or at least still be disabled after Download operation.
Actual result: The status of `PHP Language Features` extension being disabled is not captured in the settings repo, and on Download is re-enabled.

I would strongly prefer to capture this type of configuration in my settings repo, but if that's not feasible then at least on Download it shouldn't clobber this "override" if it's not able to capture it.

---

In the meantime, I think I have a workaround by using the setting `"php.suggest.basic": false,` rather than completely disabling the built-in extension. Not ideal but good enough for now. Thanks for your time and consideration.

**Comment by daiyam** [comment]
The next version should be out tomorrow with the support of the builtin extensions.

**Comment by Cottser** [comment]
I got a chance to test this today and it works great. Thanks!
