### ISSUE TITLE
All resources synced regardless of syncSettings.resources setting

### ISSUE THREAD

**Issue by max-reify** [zokugun/vscode-sync-settings#14]
- VSCode version: 1.64.2
- Sync Settings version: 0.9.0
- settings.yml
  ```yml
  hostname: ""
  profile: main
  repository:
    type: file
    path: ~/repos/config/VSCode/
   ```
- relevant parts of settings.json
  ```json
  {
    "syncSettings.resources": [
      "keybindings",
      "settings",
      "snippets"
    ],
    "syncSettings.additionalFiles": [
      "~/Library/Application Support/Code/User/globalStorage/zokugun.sync-settings/settings.yml"
    ]
  }
  ```

### Expected behavior
Since I've specified that only keybindings, settings, and snippets sync, only those settings are synced

### Actual behavior
I see these files in the target directory
```
└── profiles
    └── main
       ├── data
       │    ├── additionals
       │    │   └── ~-Library-Application Support-Code-User-globalStorage-zokugun.sync-settings-settings.yml
       │    ├── extensions.yml
       │    ├── keybindings-macos.json
       │    ├── settings.json
       │    └── ui-state.yml
       └─── .sync.yml
```
`ui-state.yml` and `extensions.yml` are both present even though I specified they should not be synced.

**Comment by daiyam** [comment]
It's weird!
Can you post the logs of the extension in the "Output" tab?

Also, there is no need to sync `~/Library/Application Support/Code/User/globalStorage/zokugun.sync-settings/settings.yml` since on new computer, you will need to repository info and profile to be able to sync it...

**Comment by max-reify** [comment]
Weirdly enough, now `ui-state.yml` and `extensions.yml` aren't getting synced. Maybe it only happened on the first sync?

**Comment by daiyam** [comment]
Weird, I don't see the `serialize extensions` or `serialize UI state` logs...

Have you done an upload before changing `syncSettings.resources`?
If yes, that would explain the issue and I will need to add a step to remove those files...

**Comment by daiyam** [comment]
> Weirdly enough, now `ui-state.yml` and `extensions.yml` aren't getting synced. Maybe it only happened on the first sync?

I think so, I didn't think of your case...

**Comment by daiyam** [comment]
The next version should be out tomorrow with the the fix for your issue.

But, synchronizing the `settings.yml` will generate an error... I will add an explanation in the README.
