### ISSUE TITLE
Should verify ensension versions before acting on them

### ISSUE THREAD

**Issue by araruna** [zokugun/vscode-sync-settings#17]
Maybe I'll improve the title later (feel free to update it if you wish), but I'm very tired right now to think of a better one...

An improvement you could make, if it is feasible to, is to compare each extension's version to the currently installed, if any, before acting on them.

What happens now seems to be that they get erased and then reinstalled. It's not a bug, but it is costful (for people with bad internet connections, for example) and wasteful in the least.

Thank you.

**Comment by daiyam** [comment]
The uninstall/install is the only hacky way I've found to be able to enable a disabled extension...
The sync doesn't care about the extension's version only if it's installed or not, enabled or not.

I did add custom commands to manage extensions in my custom version of vscode. Maybe I should make a PR to vscode...

**Comment by araruna** [comment]
Uh, ok. Then I'll close this issue and if I find the time to help figure something out I'll ask you to reopen it.

Thank you.
