### ISSUE TITLE
There should be indications that "things have changed, and they are not saved"

### ISSUE THREAD

**Issue by stdedos** [zokugun/vscode-sync-settings#19]
Related to https://github.com/zokugun/vscode-sync-settings/issues/18, there should be (regular?) information that the current settings are not saved in the repository.

I appreciate the "extra careful - I don't mess your stuff behind-the-scenes" approach, but there also needs to be way for the user to "not forget to sync", but neither "make it his second nature to touch something, and sync the settings".

The "basic model" could be periodic reminders while the settings are different from the saved ones.

The git-enhanced response gives many alternatives:

- Settings are *always* written on the cloned repo as unstaged / staged / committed in `unsaved/<yyyy-mm-dd_start>` branch, always starting a new one on top of _branch_ after the first change after uploading the settings (those branches can also exist upstream)
- (For the committed one) Uploading them means simply `git checkout <branch>; git merge --no-ff unsaved/<yyyy-mm-dd_start>; git push; git branch -m unsaved/<yyyy-mm-dd_start> _merged/unsaved/<yyyy-mm-dd_start>`

**Comment by daiyam** [comment]
@stdedos When re-reviewing your issue, I was thinking "Why not do a check every hour and alert the user if he want to save?" then I remembered the cron-related issue #28.
So in line of that issue, what if I add a `syncSettings.check` action and use an external extension to run it every hour?
Would that be ok for you?

But then the simpler `vs-cron` is deprecated and isn't available on open-vsx. I could fork it, require it and internalize the crons...
What do you think?

```
crons:
  check: 0 * * * *         // every hour
  download: 0 9 * * *  // at 9AM, every day
  upload: 0 17 * * *     // at 5PM, every day
```

**Comment by stdedos** [comment]
> ```
>   download: 0 9 * * *  // at 9AM, every day
>   upload: 0 17 * * *     // at 5PM, every day
> ```

ALL for it :star_struck: 

Remember to: **AVOID** resolving issues (e.g. `git merge ...`, etc) when you "do all that". (or do it :stuck_out_tongue_winking_eye: )

**Comment by daiyam** [comment]
The new version has the following settings https://github.com/zokugun/vscode-sync-settings#crons and a new `review` command.

Don't forget to create a new issue for your enhanced git process ;)

**Comment by stdedos** [comment]
There you go! https://github.com/zokugun/vscode-sync-settings/issues/36

I have also seen a `review` prompt; let's say verified / lgtm! :star_struck:
