### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by Tealk** [zokugun/vscode-sync-settings#2]
Hello,

you write in the readme that you can set which options you want to have synchronized, what is the default? That everything is synchronized?

Among the suggestions is also listed "snippets" is that a specific add-on?

**Comment by daiyam** [comment]
By default, `syncSettings.resources` is `["extensions", "keybindings", "settings", "snippets", "uiState"]`. So every resources are synchronized.

User Snippets: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets
