### ISSUE TITLE
Sort yml attributes

### ISSUE THREAD

**Issue by stdedos** [zokugun/vscode-sync-settings#20]
e.g. the `ui-state.yml` would be nice if it was sorted.

In my case, there seem to be changes, that I don't understand why they happen.
While trying to investigate them, the git-diff views are more complex, simply due to the fact that the yml properties are sorted in a different place on the file (in addition to containing stringified + minified json, which requires manual unpacking, if you are to investigate deeper)

**Comment by daiyam** [comment]
Yep, I can sort the attributes.

For the stringified + minified json, it's from the database.

**Comment by stdedos** [comment]
Also settings.json?

Also also, "force" trailing commas everywhere?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

(Don't worry about the JSON spec; `jsonc` (used by vscode) actually is fine with it)

**Comment by daiyam** [comment]
For `settings.json` or others, by default, the sorting will be off. Since if some users are like me, I've regrouped my settings by section (extensions, languages, ...). And when sorting, the comments might need to be removed...

**Comment by stdedos** [comment]
True dat. I'll demo it on myself and see if it's viable or not.
I'm afraid that "the most annoying thing" for me would be also loosing the whitespace among groups 😛

So far, I have neither - but unfortunately I may be becoming a vscode citizen ...

**Comment by stdedos** [comment]
Would you say that this is done now?

I can clearly see that `ui-state.yml` is sorted

**Comment by daiyam** [comment]
Yep
