### ISSUE TITLE
Should `vscode-sync-settings` do something with manually installed extensions?

### ISSUE THREAD

**Issue by stdedos** [zokugun/vscode-sync-settings#22]
I am using VSCodium, and e.g. I am unable to install `ezforo.copy-relative-path-and-line-numbers`.
Therefore, I am installing the `vsix` file manually.

I am wondering if [vscode-sync-settings](https://github.com/zokugun/vscode-sync-settings) should, e.g. pack that file on the sync repo

**Comment by daiyam** [comment]
Yes, it will.

**Comment by stdedos** [comment]
Does the above commit _mean_ that I need to _manually_ provide that file in the _aforementioned directory_, in addition to manually installing it?

**Comment by daiyam** [comment]
> I need to _manually_ provide that file in the _aforementioned directory_

Yes. I might add a command to download/update a list of extensions.

> in addition to manually installing it?

No, if it's in the list of extensions, on a new install, it will use the `.vsix`. No more manual install.

**Comment by stdedos** [comment]
> > I need to _manually_ provide that file in the _aforementioned directory_
> 
> Yes. I might add a command to download/update a list of extensions.

A yes/no dialog saying "I'm trying to upload your preferences, but X extensions are manually installed. Do you want me to automatically copy their `vsix` files?" might be awfully convenient 😃

**Comment by daiyam** [comment]
I'm trying to avoid to re-zip an extension since some extensions are changed after installed.

What if there is an extension that search/install extensions for the VS Marketplace? With the _aforementioned_ _directory_ as shadow copy.

**Comment by daiyam** [comment]
> What if there is an extension that search/install extensions for the VS Marketplace? With the _aforementioned_ _directory_ as shadow copy.

That _may_ violate their TOS (_you may install and use Marketplace Offerings only with In-Scope Products and Services._)
