### ISSUE TITLE
Does not upload the settings JSON file under WSL environment

### ISSUE THREAD

**Issue by jcchikikomori** [zokugun/vscode-sync-settings#27]
Does not recognize this file
![image](https://user-images.githubusercontent.com/4709030/187060393-ae8082d2-dd85-4ff1-9870-bc9cd1776fd5.png)

**Comment by daiyam** [comment]
You can use the setting [`"syncSettings.additionalFiles"`](https://github.com/zokugun/vscode-sync-settings#external-files) to add additional files.

**Comment by jcchikikomori** [comment]
I tried. The upload worked, but to restore is unable to restore properly
Test Cases:
* Commit without using VSCode
* Commit using online editor (Github)

![image](https://user-images.githubusercontent.com/4709030/187692109-97fd5198-ba27-4899-9ad6-9e7a04e5a4bb.png)

**Comment by daiyam** [comment]
Oh! `.vscode-server`! This isn't supported... Are you running VSCode in a browser?

**Comment by jcchikikomori** [comment]
> Oh! `.vscode-server`! This isn't supported... Are you running VSCode in a browser?

I am running VSCode (native) but connected with running WSL Distro (VSCode Server is installed inside WSL Distro)
