### ISSUE TITLE
Provide Support for WebDAV

### ISSUE THREAD

**Issue by manuth** [zokugun/vscode-sync-settings#3]
Is WebDAV as a repository backend supported?
I'd love to have my settings uploaded to my Nextcloud automatically.

Thanks a ton for your great work - it's awesome to finally have a competitor to VSCode's Settings Sync!

**Comment by daiyam** [comment]
That should be doable with the help of https://github.com/perry-mitchell/webdav-fs and some files sync.

**Comment by daiyam** [comment]
@manuth Can you try this version [sync-settings-0.6.2.vsix.zip](https://github.com/zokugun/vscode-sync-settings/files/7873670/sync-settings-0.6.2.vsix.zip)? (remove the `.zip` to install).
It's including a basic WebDAV support.

Here my test settings:
```
hostname: ""
profile: main
repository:
  type: webdav
  url: http://localhost:9988/webdav/server
  username: webdav-user
  password: pa$$w0rd!
```

All the options from https://github.com/perry-mitchell/webdav-client#client-configuration can be used.

**Comment by manuth** [comment]
Wow, that was fast!
Sadly, it doesn't seem to work. I get following error:
```
[error] Error: certificate has expired
```

In spite of this error message, my WebDAV's certificate is valid:
https://cloud.nuth.ch/

**Comment by daiyam** [comment]
Not sure what is the issue... When using your url with my fake user, I get `Error: Invalid response: 405 Not Allowed` which means, I think, that the SSL handshake was successful.

Here a new version [sync-settings-0.6.2.vsix.zip](https://github.com/zokugun/vscode-sync-settings/files/7873895/sync-settings-0.6.2.vsix.zip) which add the support for the `http(s)Agent` option.

Maybe try:
```
hostname: ""
profile: main
repository:
  type: webdav
  url: https://cloud.nuth.ch/
  username: <your username>
  password: <your password>
  agent:
    rejectUnauthorized: false
``

The agent's options are from https://nodejs.org/api/https.html#new-agentoptions or https://nodejs.org/api/tls.html#tlsconnectoptions-callback

**Comment by daiyam** [comment]
From the [NextCloud's doc](https://docs.nextcloud.com/server/latest/user_manual/en/files/access_webdav.html), the WebDAV url seems to be something like `https://cloud.nuth.ch/remote.php/dav/files/USERNAME/`.

**Comment by manuth** [comment]
> From the [NextCloud's doc](https://docs.nextcloud.com/server/latest/user_manual/en/files/access_webdav.html), the WebDAV url seems to be something like `https://cloud.nuth.ch/remote.php/dav/files/USERNAME/`.

Yeah, that's correct - this is what my URL looks like.

**Comment by daiyam** [comment]
Wait!

**Comment by daiyam** [comment]
The url should include the path of directory where your want to sync the settings.

**Comment by manuth** [comment]
It does so. I'll try the new version tomorrow.
Thank you very much for taking care 😄

**Comment by daiyam** [comment]
I've just reread my code to see I don't abusively delete files from the WebDAV. Well, right now, it's doesn't remove any files... just creates new ones.  Way too basic, I need to improve that!

But the question is should the url should include the "working" directory? Or have a separate "directory" option?
I'm worried that using unified url (server+directory) could lead to some unfortunate file deletions... Having a separate non-empty "directory" would force to user to put the correct path.

Before working with WebDAV, I will add a check to see if the directory is empty or if it contains the expected files/directories. If not, the extensions won't do anything...

**Comment by daiyam** [comment]
Here the latest version: [sync-settings-0.6.2.vsix.zip](https://github.com/zokugun/vscode-sync-settings/files/7874714/sync-settings-0.6.2.vsix.zip)

I've added a validation of the working directory. If it's empty, the extension create a file `.vsx`. If not, it matches the content of the file `.vsx` and if it doesn't match, then it generates an error.
For the upload, it firstly uploads the profiles into the temporary directory `.profiles`. When complete, it deletes the old `profiles` directory and rename `.profiles` to `profiles`. This way, I ensure the integrity of the profiles and delete only what necessary.

Tell me if it's working for you. I would then release it.
By the way, the changes are in the branch [`feat-webdav`](https://github.com/zokugun/vscode-sync-settings/tree/feat-webdav).

**Comment by manuth** [comment]
Okay, this is different - I'm getting following error now:
```
[error] Error: certificate has expired
[error] Error: The repository is not initialized
```

No idea what it's complaining about my certificate for.

**Comment by daiyam** [comment]
@manuth Is there a way for me to test with your server?

**Comment by manuth** [comment]
Sure - however, I created a temporary account. However - I'll have to delete said account once we're done with testing.
I sent you an e-mail containing the credentials.

**Comment by daiyam** [comment]
Have you send it to daiyam@zokugun.org?

**Comment by manuth** [comment]
Sorry - I had some trouble sending the e-mail.
It's sent now.

**Comment by daiyam** [comment]
Ya, I'm getting the error when running the extension. But the connection is fine when running with a test case...

**Comment by daiyam** [comment]
I'm getting the error:
```
[Extension Host] Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket._finishInit (_tls_wrap.js:932:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
```

**Comment by daiyam** [comment]
It seems to be bug with Electron (cf https://github.com/electron/electron/issues/31212).

**Comment by manuth** [comment]
Never would I have guessed that out of all possibilities it's electron causing the issue 😅
Anyways - this sure means it's working in theory (that is... until the issue in electron is fixed).

That's awesome - thanks for your effort :smile:

**Comment by daiyam** [comment]
Here the latest version [sync-settings-0.6.2.vsix.zip](https://github.com/zokugun/vscode-sync-settings/files/7875442/sync-settings-0.6.2.vsix.zip)

I've added the option `ignoreTLSErrors` to bypass that error.

Here the config used successfully:
```
repository:
  type: webdav
  url: https://cloud.nuth.ch/remote.php/dav/files/sync-settings/Apps/vscode-settings/
  username:
  password:
  ignoreTLSErrors: true
```

Feel free to clean up your WebDAV as you want :wink:

**Comment by manuth** [comment]
That's awesome! 😄 
I can confirm it's working as expected now

Thanks für taking care about it!

**Comment by daiyam** [comment]
@manuth Do you have any issue? If not, I will release the new version.

**Comment by manuth** [comment]
I have no issue - you might consider to wait until the electron error is fixed, tho (?)

Apart from that it'd be great to have this released 😄

**Comment by daiyam** [comment]
I've added to the doc: https://github.com/zokugun/vscode-sync-settings/blob/feat-webdav/docs/webdav.md#common-errors
So I think it would be fine.

**Comment by daiyam** [comment]
I've published the new version.
