### ISSUE TITLE
Hooks are not actually executed.

### ISSUE THREAD

**Issue by RayJW** [zokugun/vscode-sync-settings#39]
So like described in issue #29 I want to use the remote option to save to a repository which is not my default in the global git config.

I tried multiple approaches, but none of them work. I tried using a local git folder with the git config included and running ```git push``` and ```git pull``` via hooks, and I tried the remote repository but with setting the config via the hooks. Neither of them does what it should.

Checking the output, it seems like the hooks are not being run at all.

Just to check if I did everything right, this is what I put in my settings.json:
```
    "syncSettings.hooks.postUpload": [
        "git push origin"
    ]
```

Is there something I'm doing wrong, or is there an issue with the hooks not actually being run like they are supposed to?

**Comment by daiyam** [comment]
What's the output in the terminal?

**Comment by daiyam** [comment]
I meant what do you see in the terminal (Terminal panel)? (not logs of the extension in the Output panel)

**Comment by RayJW** [comment]
Ok, so this helped. I figured one of the issues out. So it seems like the terminal is not launched in the folder of the git repo. Thus, I have to "cd" to the correct directory first, maybe that should be documented because I assumed that the Terminal session would be in the git directory by default and not the directory of my project. But it could very well be, that this is just me. 

Another thing I noticed is, that the terminal is not reliably being launched on every run. I had to run upload a few times before the terminal actually is being created, and I think it might be that after manually closing it with the trash bin it is not being recreated until Codium has been restarted.

**Comment by daiyam** [comment]
> I have to "cd" to the correct directory first
I thought that might be the issue when re-reading my doc... I need to improve that. I just wonder what I was thinking without ironing that out.

> that the terminal is not reliably being launched on every run
I will have to test that out.

**Comment by daiyam** [comment]
@RayJW The newest should fix your issue. Reopen that issue if you still have the problem!
