### ISSUE TITLE
Command syncSettings.deleteProfile not found

### ISSUE THREAD

**Issue by cavcrosby** [zokugun/vscode-sync-settings#40]
When attempting to delete a profile that I had (via `Sync Settings: Delete a profile`), VSCodium complained that `command 'syncSettings.deleteProfile' not found`. Was this command ever implemented for the extension?

**Comment by daiyam** [comment]
Hummm, I most likely planned to do it and forgotten about it... I will fix that.

**Comment by daiyam** [comment]
@cavcrosby It's available in the latest version.
