### ISSUE TITLE
Error: Can determine binary path, when switching profiles

### ISSUE THREAD

**Issue by Checker8763** [zokugun/vscode-sync-settings#42]
**Scenario**:

- OS: Windows 10 64 Bit
- VsCodium `1.75.1 c6a9727b801542499d2b59cb7db4224e060fc578 x64`
  - installed from msi package from the Github repo
- sync methode: local git
- profiles:
  - main profile:  where i have my basic shared functionality stuff
    - rust profile (extends main) profile and rust specific extensions

Tldr: When I change betweeen the two profiles i get an error:

`Sync Settings: Error: Can determine binary path`

**Steps to reproduce**:

1. Create the profiles
2. switch from main to rust
3. install extensions
4. try and switch back
5. accept the promts for applying and restarting
6. No restart and error

**Packages:**

- Main:
  - Better Comments
  - Comment Anchors
  - (Cron Task)
  - GitLens
  - indent-rainbow
  - path Intellisense
  - PowerMode
  - Sync Settings
  - TODO highlight
  - Todo Tree
- Rust (extend Main)
  - CodeLldb
  - crates
  - even better Toml 
  - error lense
  - rustanalizer

**Comment by Checker8763** [comment]
Typo: missing space

**Comment by daiyam** [comment]
Which OS?

**Comment by Checker8763** [comment]
> Which OS? How did you install VSCodium?

Windows 10 x64

**Comment by daiyam** [comment]
A new version has been published, it should be available soon.
