### ISSUE TITLE
Remote git Permission denied

### ISSUE THREAD

**Issue by jahirfiquitiva** [zokugun/vscode-sync-settings#49]
Hi

I would like to use the extension to sync my settings into a remote GitHub private repository. But it isn't working:

```
Sync Settings: Error: The repository wasn't successfully initialized so the current operation can't continue. Please check the previous error.
```

```
Sync Settings: Error: git@github.com: Permission denied (publickey). fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.
```

I get these errors and I'm not sure what to do to fix them. I'd appreciate some help to set everything up correctly.

Thanks!

**Comment by daiyam** [comment]
> But the `git` command on your system will need to be able to read/write on the remote repository.

(from https://github.com/zokugun/vscode-sync-settings#remote-git)

To verify run the command `ssh -vT git@github.com`, you should have a log like `Hi daiyam! You've successfully authenticated, but GitHub does not provide shell access.`

Here a doc how to setup SSH for GitHub: https://docs.github.com/en/authentication/connecting-to-github-with-ssh

Then (I need to improve/fix this), you need in VSCode to run the command `Sync Settings: Reveal the repository in the file explorer`. Then in the file explorer, go up to the parent directory and delete the `repository` folder.

`Sync Settings: Upload (user -> repository)` or `Sync Settings: Download (repository -> user)` should work

**Comment by jahirfiquitiva** [comment]
@daiyam does it work with a Personal Access Token? git already works with it 🤔

**Comment by daiyam** [comment]
To use the extension, the `git` command need to able to read/write on the remote repository (in a terminal, not the git extension of VSCode).

You can use PAT but I haven't test it:
- https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
- https://www.learnhowtoprogram.com/introduction-to-programming/getting-started-with-intro-to-programming/creating-and-using-a-git-pat

**Comment by jahirfiquitiva** [comment]
@daiyam yes, that's how i use git. in a terminal, with a PAT. it works there, but not with your extension.

**Comment by daiyam** [comment]
What is your repository settings and the log in the `Sync Settings` panel of the `Output` view (menu `View` > `Output`)?

**Comment by jahirfiquitiva** [comment]
@daiyam 

```gradle
[info] repository: {"type":"git","path":"~/dev/codium","url":"git@github.com:jahirfiquitiva/codium-settings.git","branch":"main"}
[info] profile: main
[info] serialize to: /Users/jahir/dev/codium
[info] serialize extensions
[info] serialize snippets
[info] serialize UI state
[info] serialize keybindings
[info] serialize settings
[info] serialize done
[info] commit: profile(main): update -- 2023-05-25T16:03:19.756Z
[info] repository: {"type":"git","url":"git@github.com:jahirfiquitiva/codium-settings.git","branch":"main"}
[info] profile: main
[info] creating git at /Users/jahir/Library/Application Support/VSCodium/User/globalStorage/zokugun.sync-settings/repository
[info] adding new remote: git@github.com:jahirfiquitiva/codium-settings.git
[info] fetch from remote
[error] Error: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

[error] The git repository can not be pulled
[error] Error: The repository wasn't successfully initialized so the current operation can't continue. Please check the previous error.
```

**Comment by jahirfiquitiva** [comment]
@daiyam just fixed it by changing the url from `git@github` to `https`

`url: https://github.com/jahirfiquitiva/codium-settings`

btw, is it possible to sync the extensions settings? if so, how?

**Comment by daiyam** [comment]
Ya, `git@github` is for SSH.

First of, you have to use either `path` (for local git) or `url` (for remote git)

> btw, is it possible to sync the extensions settings? if so, how?

If you are talking about the other extensions settings, it should already be the case with `serialize settings` and `serialize UI state`.
If you are talking about the `settings.yml` of this extension, no you can't (since you will need a way to pull that file anyway).

**Comment by jahirfiquitiva** [comment]
@daiyam awesome, thanks for the help!
