### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by chmac** [zokugun/vscode-sync-settings#5]
I see the following while trying to enable the plugin.

```
[info] repository: {"type":"git","url":"REDACTED","branch":"main"}
[info] profile: 
[info] creating git at /Users/REDACTED/Library/Application Support/Code/User/globalStorage/zokugun.sync-settings/repository
[info] adding new remote: REDACTED
[info] fetch from remote
[error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

**Comment by chmac** [comment]
Could it be related to the fact that I'm using an empty (no commits) git repo as the target?

**Comment by chmac** [comment]
I get the same error every time after I reload VSCode, then I get the error in #6 after that. My `settings.yml` file looks like this (without any other entries):

```
repository:
  type: git
  url: REDACTED
  branch: main
```

Does the file need some extra parts? I saw there was a hostname at first, and a profile name, but I don't know what they are and they don't specify if they're required or not so I removed them.

**Comment by chmac** [comment]
I added a `profile: main` to the `settings.yml`, and I also added a commit to my repo, and now my settings are syncing successfully.

What about adding notifications on these errors / cases to tell people what to do to fix them? Or maybe my suggestion on #7 is good enough for the profile stuff. But then it would still be great to have a notification if the push fails.

**Comment by daiyam** [comment]
I will have to test if the profile's name isn't empty...

**Comment by daiyam** [comment]
I will have some improvements to add. At least, now, it's working for you.
Thx for your reports and suggestions.

**Comment by chmac** [comment]
Thanks for the plugin, great to have my settings in git! If you need any help testing releases, etc, just let me know, I'm using it on a couple of macs.
