### ISSUE TITLE
Error: The repository wasn't successfully initialized so the current operation can't continue. Please check the previous error.

### ISSUE THREAD

**Issue by anafvana** [zokugun/vscode-sync-settings#56]
Hi, there. I might need some help, because I am at a loss.

## The problem

I've been trying to set syncing up, but I keep getting the error
```
Error: The repository wasn't successfully initialized so the current operation can't continue. Please check the previous error.
```

The "previous error" I was getting was the same as issue #49 and I have fixed it accordingly. Once that was fixed, I tried running `Sync settings: Upload (user -> Repository)` and got the error above.

This is how my `settings.yml` file looks now:

```
hostname: "mac@home"

profile: main

repository:
  type: git
  url: https://github.com/anafvana/REPONAME
  branch: main
```

## Debugging steps

0. Installation
0.1. Install extension using marketplace
0.2. Run `> Sync Settings: Open the repository settings`
0.3. Populate `settings.yml` as shown above
0.4. Run `> Sync Settings: Upload (user -> repository)`
0.R. See error above and start debugging

1. Added a commit to my repo (in accordance with [this comment](https://github.com/zokugun/vscode-sync-settings/issues/5#issuecomment-1041517311) from #6)
1.R. Same error when running `Sync settings: Upload (user -> Repository)`
```
Error: The repository wasn't successfully initialized so the current operation can't continue. Please check the previous error.
```

2. `git init; git remote add origin git@github.com:anafvana/REPONAME.git; git pull` a repo in the following locations (one at a time, having unlinked the previous from git):
2.1. `/Users/USER/test`
2.2. `/Users/USER/Library/Application Support/VSCodium/User/`
2.3. `/Users/USER/Library/Application Support/VSCodium/User/globalStorage/zokugun.sync-settings`
2.R. Same error when running `Sync settings: Upload (user -> Repository)`
```
Error: The repository wasn't successfully initialized so the current operation can't continue. Please check the previous error.
```

3. Deleted the repository and re-created it
3.R. Same error when running `Sync settings: Upload (user -> Repository)`
```
Error: The repository wasn't successfully initialized so the current operation can't continue. Please check the previous error.
```

4. Attempted to delete the `profile` property, to simulate case on #5 ([this comment](https://github.com/zokugun/vscode-sync-settings/issues/5#issuecomment-1041514801))
4.R. A different error on save
```
Sync Settings: The `profile` property is required
```

5. Added back the `profile` property
5.R. Two new errors on save
```
Sync Settings: Error: fatal: could not read Username for 'https://github.com': Device not configured
```

```
Sync Settings: The git repository can not be pulled
```

6. Cloned the re-created repo to my machine to `/Users/USER/REPONAME`
6.R. Same error when running `Sync settings: Upload (user -> Repository)`
```
Error: The repository wasn't successfully initialized so the current operation can't continue. Please check the previous error.
```

7. Moved the .git folder into:
7.1. `/Users/USER/Library/Application Support/VSCodium/User/`
7.2. `/Users/USER/Library/Application Support/VSCodium/User/globalStorage/zokugun.sync-settings`
7.R. Same error when running `Sync settings: Upload (user -> Repository)`
```
Error: The repository wasn't successfully initialized so the current operation can't continue. Please check the previous error.
```

<details>

<summary>📜 Output > Sync Settings 📜</summary>

The output has been redacted for brevity due to repeated error messages/blocks.

```
[info] repository: {"type":"git","url":"https://github.com/anafvana/REPONAME","branch":"main"}
[info] profile: main
[info] hostname: mac@home
[error] Error: fatal: could not read Username for 'https://github.com': Device not configured
[...]
[error] The git repository can not be pulled
[error] Error: The repository wasn't successfully initialized so the current operation can't continue. Please check the previous error.
[...]
[info] repository: {"type":"git","url":"https://github.com/anafvana/REPONAME","branch":"main"}
[error] The `profile` property is required
[...]
[info] repository: {"type":"git","url":"https://github.com/anafvana/REPONAME","branch":"main"}
[info] profile: main
[info] hostname: mac@home
[info] creating git at /Users/USER/Library/Application Support/VSCodium/User/globalStorage/zokugun.sync-settings/repository
[info] adding new remote: https://github.com/anafvana/REPONAME
[info] fetch from remote
[error] Error: fatal: could not read Username for 'https://github.com': Device not configured

[error] The git repository can not be pulled
[error] Error: The repository wasn't successfully initialized so the current operation can't continue. Please check the previous error.
[...]
[info] repository: {"type":"git","url":"https://github.com/anafvana/REPONAME","branch":"main"}
[info] profile: main
[info] creating git at /Users/USER/Library/Application Support/VSCodium/User/globalStorage/zokugun.sync-settings/repository
[info] adding new remote: https://github.com/anafvana/REPONAME
[info] fetch from remote
[error] Error: fatal: could not read Username for 'https://github.com': Device not configured
```

</details>

My `git` command is working perfectly fine from the terminal. It is all I ever use, but here is the output:

```
% ssh -T git@github.com 
Enter passphrase for key '/Users/USER/.ssh/id_rsa': 
Hi anafvana! You've successfully authenticated, but GitHub does not provide shell access.
```

## My questions

1. **Should I add something to `profile.yaml`?** I see it is empty (`> Sync settings: Reveal the profile in the file explorer`) but I found nothing in the docs
2. **Is this supposed to be repo-specific?** I have been assuming it was VSC-wide, but at this point I am reaching for answers. So I've started to wonder if the issue is that the project I have been working on is not set as a repository yet, and the extension is unable to find a repository in that project (which doesn't really make sense considering the logs, but *leave no stone unturned*, they say.
3. **Am I supposed to also specify a local repository?** My goal is only to sync it to GitHub direct from the source. The docs don't mention the need to add *both* a path and a URL, and I can't really re-use the `repository` key
4. **What am I missing here?** From my understanding, I have followed the documentation step by step, but it's not working. Has my 🐠 fish 🐠 brain failed me?

P.S.: I need this extension because I use VSCod**ium**, which [doesn't have this option](https://github.com/VSCodium/vscodium/issues/482)

**Comment by anafvana** [comment]
P.P.S.: I have tried to restart VSCodium. No changes to my predicament

**Comment by daiyam** [comment]
Since you have tried lot of think, I would delete the directory `/Users/USER/Library/Application Support/VSCodium/User/globalStorage/zokugun.sync-settings` to start from a clean state.

Then, make sure that you have read/write access to the repo in the command line. Do a `git clone git@github.com:anafvana/REPONAME.git` somewhere.

Then, add the config with `> Sync Settings: Open the repository settings` with the `git@github.com:anafvana/REPONAME.git` as url like:

```
hostname: "mac@home"

profile: main

repository:
  type: git
  url: git@github.com:anafvana/REPONAME.git
  branch: main
```

Finally, do `Sync settings: Upload (user -> Repository)`

To your question,
1. You can leave it empty. It's used when a profile extends another.
2. It should be useable for any editor based on VSCode.
3. No. The extension keeps a local copy (to do the pulls and commits) at in `/Users/USER/Library/Application Support/VSCodium/User/globalStorage/zokugun.sync-settings/repository`
4. The first thing is that the extension doesn't create the remote repository. The second one is an `https` url can be tricky for the write access.


Here my config:
```
hostname: ""
profile: main

repository:
  type: git
  url: git@github.com:daiyam/mrcode-settings.git
```

PS: I'm the main maintainer of VSCodium :wink:

**Comment by anafvana** [comment]
Hei,

First of all, thank you so much for the (super quick) response!

I found out what the issue was, after all: **my SSH key required a password**.

If anyone is having the same problem as me, I warn you that just removing the password was not enough at first. I had to follow @daiyam's suggestion as well. 


## Step-by-step

N.B.: **The repo I used already had one commit**, from my previous debug attempts (suggested on [this comment](https://github.com/zokugun/vscode-sync-settings/issues/5#issuecomment-1041517311)). If you want to have the exact same environment as me, then add an empty file to the repo 

1. `ssh-keygen -p` and make the new password **empty**
2. `rm -rf /Users/USER/Library/Application Support/VSCodium/User/globalStorage/zokugun.*`
3. Uninstall Settings Sync and Cron Tasks
4. Restart VSCodium
5. Re-install Settings Sync
6. Run `git clone git@github.com:USERNAME/REPONAME.git` wherever, just to make sure all is good
7. Run `> Sync Settings: Open the repository settings`
8. Write your config. Mine is:
```hostname: "mac@home"

profile: main

repository:
  type: git
  url: git@github.com:anafvana/REPONAME.git
  branch: main
```
9. Run `> Sync settings: Upload (user -> Repository)`
10. Check your repo!

## Final considerations

1. Could I maybe suggest the feature to handle SSH keys with passwords, @daiyam ? (Can create a separate issue, if you want)
2. Do you know if the repo being empty is still an issue (from [this comment](https://github.com/zokugun/vscode-sync-settings/issues/5#issuecomment-1041517311))?
3. Thank you SO much for the availability to help
4. Thank you for both this extension and for keeping VSCodium in our lives ❤️

**Comment by daiyam** [comment]
> Could I maybe suggest the feature to handle SSH keys with passwords

Ya, I've not tested that. I will have to think about it.

> Do you know if the repo being empty is still an issue

It should be fine as long as the repository exists.
