### ISSUE TITLE
Error: The repository is not initialized

### ISSUE THREAD

**Issue by chmac** [zokugun/vscode-sync-settings#6]
I get this error when I try to upload my settings. However, I need to open the "output" tab to see it. If the operation fails, it would be great if there was a notification generated.

Also, it would be awesome if the plugin would explain what the solution to this issue is. Maybe like I mentioned in #5, maybe it's because my git repo has no commits?

**Comment by daiyam** [comment]
You should had a previous error before that one. Yes, some notifications are required.

**Comment by chmac** [comment]
Yeah, I saw the error in #5 first, and then this one.
