### ISSUE TITLE
Additional file Windows path

### ISSUE THREAD

**Issue by Johnymalina** [zokugun/vscode-sync-settings#76]
Hi,

iam having problem to sync files on windows. I documentation is just an example of Linux path so i tried it like this

`"syncSettings.additionalFiles": ["C:\\Users\\Username\\.ssh\\config"]`

but it does crate file named C and its empty. Does this feature works on Windows or its just syntax wrong?

Thanks

**Comment by daiyam** [comment]
Yes, there is an issue with static paths like `C:\\Users\\Username\\.ssh\\config`. The filename of the backup should be `c--Users-Username-.ssh-config` but the `:` isn't replaced.

But anyway, you should can use `"syncSettings.additionalFiles": ["~/.ssh/config"]` which will work even if you username is different.

**Comment by Johnymalina** [comment]
Now it works. Thanks
