### ISSUE TITLE
Is the settings.yml file reloaded on change?

### ISSUE THREAD

**Issue by chmac** [zokugun/vscode-sync-settings#9]
I've found that after changing settings I need to run the "Reload Window" command to restart VSCode otherwise my changes to the remotes are not picked up from `settings.yml`.

**Comment by daiyam** [comment]
Yep, it's broken!

**Comment by daiyam** [comment]
I've found the issue! I'm using `vscode.workspace.createFileSystemWatcher` and found this in vscode source code:

```
// 1.64.x behaviour change: given the new support to watch any folder
// we start to ignore events outside the workspace when only a string
// pattern is provided to avoid sending events to extensions that are
// unexpected.
```

Since `settings.yml` is outside the workspace the extension doesn't get the events...
